import React from "react";
import Footer from "../Footer";
import HeaderMenu from "../HeaderMenu";
import Head from "next/head";
import LandingPage from "../LandingPage";

export default function Layout({ children }: any): JSX.Element {
  return (
    <>
      <HeaderMenu />
      <Head>
        <title>Sweetpot | Multi-Chain Statistics </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
      {children}
      <Footer />
    </>
  );
}
